# Generated by Django 4.2.2 on 2023-07-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSKEY',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='', max_length=50)),
                ('aws_access', models.CharField(default='', max_length=40)),
                ('aws_secret', models.CharField(default='', max_length=50)),
                ('aws_token', models.CharField(default='', max_length=900)),
                ('aws_region', models.CharField(default='', max_length=20)),
                ('aws_profile', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EC2',
            fields=[
                ('idx', models.BigAutoField(primary_key=True, serialize=False)),
                ('MyResourceName', models.CharField(default='', max_length=20)),
                ('MyResourceType', models.CharField(default='', max_length=10)),
                ('MyResourceDetails', models.CharField(default='', max_length=10)),
                ('MyResourceGrade', models.CharField(default='', max_length=10)),
                ('PlatformDetails', models.CharField(default='', max_length=20)),
                ('InstanceId', models.CharField(default='', max_length=30)),
                ('KeyName', models.CharField(default='', max_length=20)),
                ('InstanceType', models.CharField(default='', max_length=15)),
                ('AvailabilityZone', models.CharField(default='', max_length=20)),
                ('PrivateIp', models.CharField(default='', max_length=20)),
                ('PbulicIp', models.CharField(default='', max_length=20)),
                ('PublicDns', models.CharField(default='', max_length=100)),
                ('Tags', models.TextField(default='')),
            ],
        ),
    ]
